# Permalinks
permalink:        '/:title'
relative_permalinks: true

# Setup
title:            Dan Santos
tagline:          'r00by n00by'
url:              https://canigetapickle.github.io
paginate:         3
baseurl:          /
author:           
  name:           'Dan Santos'
  url:            
  email:          danielrobertsantos@gmail.com

# Custom vars
version:          1.0.0
github:           
  repo:           https://github.com/canigetapickle/canigetapickle.github.io
excerpt_separator: "<!--end-excerpt-->"
  
# Nav bar
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Jekyll Sitemap Generator
gems:
  - jekyll-sitemap